### ISSUE TITLE
Is it possible to add any channel right to the .evn?

### ISSUE THREAD

**Issue by DSDV** [Domenikus/channel-creator-bot#4]
Hi, 

thank you for your script and work (: 
is it possible to add any give teamspeak channel permission to the .env? 
(like setting the voice quality and channel icon)

with kind regards

**Comment by Domenikus** [comment]
Hi, 

functionality does not exist yet. What permissions do you need?

Regarding setting a channel icon, you would need to know the icon ID, which you can only get via server query. If this is not an issue for you I can implement it as well.

Best,
Dominik

**Comment by Domenikus** [comment]
Hi @DSDV, 

I published version v1.2.0. You are now able to provide channel codec and coded quailty via environment variable.

Best,
Dominik

**Comment by DSDV** [comment]
Hi, 
and thanks for the work /sorry for my late reply. 
(we had a server migration and got our sinus bot up and running again). 

i personally don't like the musicbot and that it needs a full team speak installation. 
But the scripting add-ons are just so feature rich. 

What we needed looked like that: 
![Expanding Channel Config](https://github.com/Domenikus/channel-creator-bot/assets/5504857/f3ad1a1a-ce59-4178-a9b6-90614a9ff773)

**Comment by Domenikus** [comment]
Hi,

got it. Currently you can set everything you can set in channel creation except, icon, encryption and file permissions.

Anyway thanks for the feedback and impressions to improve.

Best Dominik
